"""
Django settings for Incident project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import sys

# Monkey patch for Django 6.0 SQLite compatibility
# Add missing getlimit method to SQLite connection
def _getlimit(self, category):
    """Get SQLite limit for the given category"""
    # SQLite limit categories
    SQLITE_LIMIT_LENGTH = 0
    SQLITE_LIMIT_SQL_LENGTH = 1
    SQLITE_LIMIT_COLUMN = 2
    SQLITE_LIMIT_EXPR_DEPTH = 3
    SQLITE_LIMIT_COMPOUND_SELECT = 4
    SQLITE_LIMIT_VDBE_OP = 5
    SQLITE_LIMIT_FUNCTION_ARG = 6
    SQLITE_LIMIT_ATTACHED = 7
    SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8
    SQLITE_LIMIT_VARIABLE_NUMBER = 9
    SQLITE_LIMIT_TRIGGER_DEPTH = 10
    SQLITE_LIMIT_WORKER_THREADS = 11
    
    # Default limits for SQLite (can be queried with PRAGMA)
    limits = {
        SQLITE_LIMIT_LENGTH: 1000000000,
        SQLITE_LIMIT_SQL_LENGTH: 1000000000,
        SQLITE_LIMIT_COLUMN: 2000,
        SQLITE_LIMIT_EXPR_DEPTH: 1000,
        SQLITE_LIMIT_COMPOUND_SELECT: 500,
        SQLITE_LIMIT_VDBE_OP: 250000000,
        SQLITE_LIMIT_FUNCTION_ARG: 127,
        SQLITE_LIMIT_ATTACHED: 10,
        SQLITE_LIMIT_LIKE_PATTERN_LENGTH: 50000,
        SQLITE_LIMIT_VARIABLE_NUMBER: 32766,
        SQLITE_LIMIT_TRIGGER_DEPTH: 1000,
        SQLITE_LIMIT_WORKER_THREADS: 0,
    }
    return limits.get(category, -1)

# Apply the patch to both sqlite3 and pysqlite3 (if available)
# Some systems use pysqlite3 which also needs the patch
def _patch_sqlite_module(module):
    """Patch a SQLite module's Connection class with getlimit method"""
    if hasattr(module, 'Connection') and not hasattr(module.Connection, 'getlimit'):
        try:
            # Try direct assignment first
            module.Connection.getlimit = _getlimit
        except TypeError:
            # If the Connection type is immutable, use a wrapper class
            _OriginalConnection = module.Connection
            
            class ConnectionWrapper(_OriginalConnection):
                def getlimit(self, category):
                    return _getlimit(self, category)
            
            # Replace the Connection class in the module
            module.Connection = ConnectionWrapper

# Patch standard sqlite3
try:
    import sqlite3
    _patch_sqlite_module(sqlite3)
except ImportError:
    pass

# Patch pysqlite3 if it's installed
try:
    from pysqlite3 import dbapi2 as pysqlite3
    _patch_sqlite_module(pysqlite3)
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m42r!p9a^ab0bli8i*mxzh4%j3gj52%dt==hs*p#-uwpqe=u75'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    
    # Local apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Incident.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Incident.wsgi.application'

# ASGI Configuration for WebSockets
ASGI_APPLICATION = 'Incident.asgi.application'

# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),  # 2 hours as requested
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),  # 2 days as requested
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

# Email Configuration
# For testing with real email, uncomment SMTP backend and add your app password
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For now, prints to console
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'me.mohamed.eid0@gmail.com'
EMAIL_HOST_PASSWORD = 'fioe okhq jcjv gqnx'  # Add Gmail App Password here (not your regular password)
DEFAULT_FROM_EMAIL = 'me.mohamed.eid0@gmail.com'

# Frontend URL for email links (update for production)
FRONTEND_URL = 'http://localhost:8000'

# CORS Configuration
# Allow all origins and methods (development/testing)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# *********************************************************
# For production, specify allowed origins like below:
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'https://yourdomain.com'
# ]

# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow all headers
CORS_ALLOW_HEADERS = [
    '*',
]

# Expose all headers
CORS_EXPOSE_HEADERS = [
    '*',
]

# Allow unsafe origins (HTTP and HTTPS mixing)
CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = []

# WhatsApp Cloud API Configuration (Meta Business)
# Get credentials from: https://developers.facebook.com
# Setup guide:
#   1. Go to https://developers.facebook.com
#   2. Create/Select App → Add WhatsApp Product
#   3. Go to WhatsApp → API Setup
#   4. Get Temporary Access Token and Phone Number ID
#   5. For permanent token: Settings → Business Settings → System Users → Create token
WHATSAPP_ACCESS_TOKEN = 'your_access_token_here'  # Get from Facebook Business Manager
WHATSAPP_PHONE_NUMBER_ID = 'your_phone_number_id_here'  # Get from WhatsApp API Setup page
WHATSAPP_API_VERSION = 'v21.0'  # Current WhatsApp API version
