# Generated by Django 6.0 on 2025-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='core_ticket_assigne_501871_idx',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='project_name',
            field=models.CharField(default='Unknown Project', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_breached',
            field=models.BooleanField(default=False, help_text='If resolution SLA was breached'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, help_text='Expected resolution time (set by admin)', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_breached',
            field=models.BooleanField(default=False, help_text='If response SLA was breached'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_due_at',
            field=models.DateTimeField(blank=True, help_text='When admin should respond/open ticket (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='file_data',
            field=models.BinaryField(default=b'', help_text='Binary file data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SYSTEM', 'System Alert')], default='EMAIL', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('PROBLEM', 'Problem'), ('SERVICE_DOWN', 'Service Down'), ('NEW_FEATURE', 'New Feature Request')], default='PROBLEM', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPENED', 'Opened'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('WAITING_APPROVAL', 'Waiting for Client Approval'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='status_from',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('OPENED', 'Opened'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('WAITING_APPROVAL', 'Waiting for Client Approval'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='status_to',
            field=models.CharField(choices=[('NEW', 'New'), ('OPENED', 'Opened'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('WAITING_APPROVAL', 'Waiting for Client Approval'), ('CLOSED', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin'), ('SUPPORT', 'Developer')], default='CLIENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Phone number for WhatsApp notifications', max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
