# Generated by Django 6.0 on 2025-12-23 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project_name',
            field=models.CharField(default='General', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'SUPPORT'}, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
